### ISSUE TITLE
loads required to run the ins-service example

### ISSUE THREAD

**Issue by amissine** [bitfinexcom/svc-js-cli#16]
alec@alec-MS-7623 ~/process/grenache-grape $ svc-js-cli init grenache-api-base dns-service 1337 ./bfx-util-js
ERR! Cannot find module 'lodash' 
ERR! Error: Cannot find module 'lodash'
ERR!     at Function.Module._resolveFilename (module.js:536:15)
ERR!     at Function.Module._load (module.js:466:25)
ERR!     at Module.require (module.js:579:17)
ERR!     at require (internal/module.js:11:18)
ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/svc-js-cli/lib/cmds/init.js:7:11)
ERR!     at Module._compile (module.js:635:30)
ERR!     at Object.Module._extensions..js (module.js:646:10)
ERR!     at Module.load (module.js:554:32)
ERR!     at tryModuleLoad (module.js:497:12)
ERR!     at Function.Module._load (module.js:489:3)
ERR! 
ERR! 
ERR! svc-js-cli: 1.0.0 node: v8.9.1
ERR! please open an issue including this log on https://github.com/bitfinexcom/svc-js-cli/issues
alec@alec-MS-7623 ~/process/grenache-grape $ sudo npm i -g lodash
/usr/local/lib
└── lodash@4.17.10 

Fixed - having installed lodash everything runs just fine. Thanks a lot for your wonderful work, folks!
:)

**Comment by amissine** [comment]
Typo: dns-service example

Sorry about that.

**Comment by amissine** [comment]
Another typo: lodash required to run the dns-service example. Bloody autocomplete!
:)

**Comment by robertkowalski** [comment]
for a hotfix, just rerun npm install again, somehow npm seems to delete other module directories when adding git based repos.

working on a fix..
